// Generated automatically by nearley
// http://github.com/Hardmath123/nearley
(function () {
function id(x) {return x[0]; }
var grammar = {
    ParserRules: [
    {"name": "dqstring$ebnf$1", "symbols": []},
    {"name": "dqstring$ebnf$1", "symbols": ["dstrchar", "dqstring$ebnf$1"]},
    {"name": "dqstring", "symbols": [{"literal":"\""}, "dqstring$ebnf$1", {"literal":"\""}]},
    {"name": "sqstring$ebnf$1", "symbols": []},
    {"name": "sqstring$ebnf$1", "symbols": ["sstrchar", "sqstring$ebnf$1"]},
    {"name": "sqstring", "symbols": [{"literal":"'"}, "sqstring$ebnf$1", {"literal":"'"}]},
    {"name": "btstring$ebnf$1", "symbols": []},
    {"name": "btstring$ebnf$1", "symbols": [/[^`]/, "btstring$ebnf$1"]},
    {"name": "btstring", "symbols": [{"literal":"`"}, "btstring$ebnf$1", {"literal":"`"}]},
    {"name": "dstrchar", "symbols": [/[^\\"\n]/]},
    {"name": "dstrchar", "symbols": [{"literal":"\\"}, "strescape"]},
    {"name": "sstrchar", "symbols": [/[^\\'\n]/]},
    {"name": "sstrchar", "symbols": [{"literal":"\\"}, "strescape"]},
    {"name": "strescape", "symbols": [/["'\\/bfnrt]/]},
    {"name": "strescape", "symbols": [{"literal":"u"}, /[a-fA-F0-9]/, /[a-fA-F0-9]/, /[a-fA-F0-9]/, /[a-fA-F0-9]/]},
    {"name": "main", "symbols": ["program"]},
    {"name": "program$ebnf$1", "symbols": []},
    {"name": "program$ebnf$1", "symbols": ["commands", "program$ebnf$1"]},
    {"name": "program", "symbols": ["program$ebnf$1"]},
    {"name": "commands$ebnf$1$subexpression$1", "symbols": ["_", "command"]},
    {"name": "commands$ebnf$1", "symbols": ["commands$ebnf$1$subexpression$1"]},
    {"name": "commands$ebnf$1", "symbols": []},
    {"name": "commands", "symbols": ["commands$ebnf$1", "_", "newline"]},
    {"name": "command", "symbols": ["comment"]},
    {"name": "command", "symbols": ["define"]},
    {"name": "command", "symbols": ["modify"]},
    {"name": "command", "symbols": ["call"]},
    {"name": "command", "symbols": ["conditional"]},
    {"name": "command", "symbols": ["command", "_", "comment"]},
    {"name": "comment$ebnf$1", "symbols": []},
    {"name": "comment$ebnf$1", "symbols": [/[^"\n"]/, "comment$ebnf$1"]},
    {"name": "comment", "symbols": ["_", {"literal":"#"}, "_", "comment$ebnf$1"]},
    {"name": "expression", "symbols": ["arithmetic"]},
    {"name": "expression", "symbols": ["block"]},
    {"name": "conditional$string$1", "symbols": [{"literal":"i"}, {"literal":"f"}]},
    {"name": "conditional$string$2", "symbols": [{"literal":"e"}, {"literal":"n"}, {"literal":"d"}]},
    {"name": "conditional", "symbols": ["conditional$string$1", "__", "expression", "__", "block", "conditional$string$2"]},
    {"name": "conditional$string$3", "symbols": [{"literal":"i"}, {"literal":"f"}]},
    {"name": "conditional$string$4", "symbols": [{"literal":"e"}, {"literal":"l"}, {"literal":"s"}, {"literal":"e"}]},
    {"name": "conditional$string$5", "symbols": [{"literal":"e"}, {"literal":"n"}, {"literal":"d"}]},
    {"name": "conditional", "symbols": ["conditional$string$3", "__", "expression", "__", "block", "conditional$string$4", "block", "conditional$string$5"]},
    {"name": "define$string$1", "symbols": [{"literal":"n"}, {"literal":"u"}, {"literal":"m"}, {"literal":" "}]},
    {"name": "define$ebnf$1$subexpression$1", "symbols": ["__", "setter", "__", "expression"]},
    {"name": "define$ebnf$1", "symbols": ["define$ebnf$1$subexpression$1"]},
    {"name": "define$ebnf$1", "symbols": []},
    {"name": "define", "symbols": ["define$string$1", "var", "define$ebnf$1"]},
    {"name": "define$string$2", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":" "}]},
    {"name": "define$ebnf$2$subexpression$1", "symbols": ["__", "setter", "__", "expression"]},
    {"name": "define$ebnf$2", "symbols": ["define$ebnf$2$subexpression$1"]},
    {"name": "define$ebnf$2", "symbols": []},
    {"name": "define", "symbols": ["define$string$2", "var", "define$ebnf$2"]},
    {"name": "define$string$3", "symbols": [{"literal":"b"}, {"literal":"o"}, {"literal":"o"}, {"literal":"l"}, {"literal":" "}]},
    {"name": "define$ebnf$3$subexpression$1", "symbols": ["__", "setter", "__", "expression"]},
    {"name": "define$ebnf$3", "symbols": ["define$ebnf$3$subexpression$1"]},
    {"name": "define$ebnf$3", "symbols": []},
    {"name": "define", "symbols": ["define$string$3", "var", "define$ebnf$3"]},
    {"name": "modify", "symbols": ["var", "__", "setter", "__", "expression"]},
    {"name": "setter", "symbols": [{"literal":"="}]},
    {"name": "setter$string$1", "symbols": [{"literal":"i"}, {"literal":"s"}]},
    {"name": "setter", "symbols": ["setter$string$1"]},
    {"name": "call", "symbols": ["var", "__", "args"]},
    {"name": "call", "symbols": ["var"]},
    {"name": "call$ebnf$1", "symbols": ["args"]},
    {"name": "call$ebnf$1", "symbols": []},
    {"name": "call", "symbols": ["var", {"literal":"("}, "_", "call$ebnf$1", "_", {"literal":")"}]},
    {"name": "args$ebnf$1", "symbols": []},
    {"name": "args$ebnf$1", "symbols": ["arg", "args$ebnf$1"]},
    {"name": "args", "symbols": ["args$ebnf$1", "expression"]},
    {"name": "arg", "symbols": ["expression", "_", {"literal":","}, "_"]},
    {"name": "arithmetic", "symbols": ["_", "AS", "_"]},
    {"name": "block$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}]},
    {"name": "block$ebnf$1", "symbols": ["newline"]},
    {"name": "block$ebnf$1", "symbols": []},
    {"name": "block$ebnf$2", "symbols": ["newline"]},
    {"name": "block$ebnf$2", "symbols": []},
    {"name": "block", "symbols": ["block$string$1", "_", "block$ebnf$1", "program", "_", "block$ebnf$2"]},
    {"name": "B", "symbols": [{"literal":"("}, "_", "AS", "_", {"literal":")"}]},
    {"name": "B", "symbols": ["float"]},
    {"name": "B", "symbols": ["int"]},
    {"name": "B", "symbols": ["var"]},
    {"name": "B", "symbols": ["string"]},
    {"name": "B", "symbols": ["bool"]},
    {"name": "I", "symbols": ["B", "_", {"literal":"^"}, "_", "I"]},
    {"name": "I", "symbols": ["B"]},
    {"name": "DM", "symbols": ["DM", "_", {"literal":"*"}, "_", "I"]},
    {"name": "DM", "symbols": ["DM", "_", {"literal":"/"}, "_", "I"]},
    {"name": "DM$string$1", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"i"}, {"literal":"m"}, {"literal":"e"}, {"literal":"s"}, {"literal":" "}]},
    {"name": "DM", "symbols": ["DM", "DM$string$1", "I"]},
    {"name": "DM$string$2", "symbols": [{"literal":" "}, {"literal":"d"}, {"literal":"i"}, {"literal":"v"}, {"literal":"i"}, {"literal":"d"}, {"literal":"e"}, {"literal":" "}]},
    {"name": "DM", "symbols": ["DM", "DM$string$2", "I"]},
    {"name": "DM$string$3", "symbols": [{"literal":" "}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}]},
    {"name": "DM", "symbols": ["DM", "DM$string$3", "I"]},
    {"name": "DM", "symbols": ["I"]},
    {"name": "AS", "symbols": ["AS", "_", {"literal":"+"}, "_", "DM"]},
    {"name": "AS", "symbols": ["AS", "_", {"literal":"-"}, "_", "DM"]},
    {"name": "AS$string$1", "symbols": [{"literal":" "}, {"literal":"l"}, {"literal":"e"}, {"literal":"s"}, {"literal":"s"}, {"literal":" "}]},
    {"name": "AS", "symbols": ["AS", "AS$string$1", "DM"]},
    {"name": "AS$string$2", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":" "}]},
    {"name": "AS", "symbols": ["AS", "AS$string$2", "DM"]},
    {"name": "AS$string$3", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"l"}, {"literal":"u"}, {"literal":"s"}, {"literal":" "}]},
    {"name": "AS", "symbols": ["AS", "AS$string$3", "DM"]},
    {"name": "AS", "symbols": ["DM"]},
    {"name": "float$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "float$ebnf$1", "symbols": [/[0-9]/, "float$ebnf$1"]},
    {"name": "float", "symbols": ["int", {"literal":"."}, "float$ebnf$1"]},
    {"name": "int$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "int$ebnf$1", "symbols": [/[0-9]/, "int$ebnf$1"]},
    {"name": "int", "symbols": ["int$ebnf$1"]},
    {"name": "string", "symbols": ["dqstring"]},
    {"name": "string", "symbols": ["sqstring"]},
    {"name": "string", "symbols": ["btstring"]},
    {"name": "bool$string$1", "symbols": [{"literal":"t"}, {"literal":"r"}, {"literal":"u"}, {"literal":"e"}]},
    {"name": "bool", "symbols": ["bool$string$1"]},
    {"name": "bool$string$2", "symbols": [{"literal":"y"}, {"literal":"e"}, {"literal":"s"}]},
    {"name": "bool", "symbols": ["bool$string$2"]},
    {"name": "bool$string$3", "symbols": [{"literal":"f"}, {"literal":"a"}, {"literal":"l"}, {"literal":"s"}, {"literal":"e"}]},
    {"name": "bool", "symbols": ["bool$string$3"]},
    {"name": "bool$string$4", "symbols": [{"literal":"n"}, {"literal":"o"}]},
    {"name": "bool", "symbols": ["bool$string$4"]},
    {"name": "var$ebnf$1", "symbols": ["varchar"]},
    {"name": "var$ebnf$1", "symbols": ["varchar", "var$ebnf$1"]},
    {"name": "var", "symbols": ["var$ebnf$1"]},
    {"name": "varchar", "symbols": [/./]},
    {"name": "newline", "symbols": [{"literal":"\r"}, {"literal":"\n"}]},
    {"name": "newline", "symbols": [{"literal":"\r"}]},
    {"name": "newline", "symbols": [{"literal":"\n"}]},
    {"name": "newline", "symbols": [{"literal":";"}]},
    {"name": "_$ebnf$1", "symbols": []},
    {"name": "_$ebnf$1", "symbols": [{"literal":" "}, "_$ebnf$1"]},
    {"name": "_", "symbols": ["_$ebnf$1"]},
    {"name": "__$ebnf$1", "symbols": [{"literal":" "}]},
    {"name": "__$ebnf$1", "symbols": [{"literal":" "}, "__$ebnf$1"]},
    {"name": "__", "symbols": ["__$ebnf$1"]}
]
  , ParserStart: "main"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
