<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>loli</string>
	</array>
	<key>name</key>
	<string>nanalang</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>((?!-)(?&lt;=\W)|^)(win|lose)(?!-)(?=\W)</string>
			<key>name</key>
			<string>constant.language.loli</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([0-9]+(\.[0-9]+)?)</string>
			<key>name</key>
			<string>constant.numeric.loli</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:^|\s)(is|issa|+|\-|/|*|\^|times|over|less|plus|add)\s</string>
			<key>name</key>
			<string>keyword.operator.loli</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*(if|elsz|gtfo)(?=\s|,|$)</string>
			<key>name</key>
			<string>keyword.control.loli</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*(btw\ )</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.number-sign.loli</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.loli</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.loli</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.loli</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.loli</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>end</key>
			<string>`</string>
			<key>name</key>
			<string>string.quoted.other.loli</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.loli</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*(rite|cri)</string>
			<key>name</key>
			<string>support.function.core.loli</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([^()&lt;&gt;. +\-*/^\\!#=\'",!{}\n]+)</string>
			<key>name</key>
			<string>variable.parameter.loli</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.loli</string>
	<key>uuid</key>
	<string>2d04c2dc-793e-4c10-bb55-9524ad865284</string>
</dict>
</plist>
