<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lolly</string>
	</array>
	<key>name</key>
	<string>nanalang</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>((?!-)(?&lt;=\W)|^)(win|lose)(?!-)(?=\W)</string>
			<key>name</key>
			<string>constant.language.lolly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([0-9]+(\.[0-9]+)?)</string>
			<key>name</key>
			<string>constant.numeric.lolly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:^|\s)(is|issa|+|\-|/|*|\^|times|over|less|plus|add)\s</string>
			<key>name</key>
			<string>keyword.operator.lolly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*(if|elsz|gtfo|end|tri|cat|howto)(\s|,|:|\.\.\.|$)</string>
			<key>name</key>
			<string>keyword.control.lolly</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*(btw\ )</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.number-sign.lolly</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.lolly</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.lolly</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.lolly</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.lolly</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>end</key>
			<string>`</string>
			<key>name</key>
			<string>string.quoted.other.lolly</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.lolly</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*(rite|cri)</string>
			<key>name</key>
			<string>support.function.core.lolly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([^()&lt;&gt;. +\-*/^\\!#=\'",!{}:]+)</string>
			<key>name</key>
			<string>variable.other.lolly</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.lolly</string>
	<key>uuid</key>
	<string>2d04c2dc-793e-4c10-bb55-9524ad865284</string>
</dict>
</plist>
